[package]
name = "osc-heartrate-monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
btleplug = "0.11.5"
tokio = { version = "1.39.2", features = ["full"] }
tokio-stream = "0.1.15"
uuid = "1.10.0"
